name: dsh-web-search-multi

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
